#应用组织信息（可选）
app: checkin # 应用名称。留空则默认取当前组件的实例名称为app名称。
# stage: '' # 环境名称。默认值是 dev。建议使用 ${env.STAGE} 变量定义环境名称
#组件信息
component: scf # (必选) 组件名称，在该实例中为 scf
name: checkin # (必选) 组件实例名称。
#组件参数配置，根据每个组件，实现具体的资源信息配置
inputs:
  name: ${app} # 云函数名称，默认为 ${name}-${stage}-${app}
  src: ./ # 项目代码路径，默认写法，新建特定命名的 COS Bucket 并上传
  handler: invite_user.main #入口
  runtime: Python3.6 # 运行环境 默认 Nodejs10.15
  region: ap-guangzhou # 函数所在区域
  description: 上下班签到脚本
  timeout: 60
  environment: #  环境变量
    variables: #  环境变量对象
      TZ: Asia/Shanghai
  events: # 触发器配置
    - timer: # 定时触发器
        parameters:
          cronExpression: '* 30 9,18 * * * *'
          enable: true